"use client";
import * as React from "react";
import { motion } from "framer-motion";
import { useAppStore } from "@/store/useAppStore";
import { Card } from "@/components/ui/Card";
import { Share2, Download, CheckCircle2 } from "lucide-react";
import { cn } from "@/utils/cn";
import { getBadgeById } from "@/lib/gamificationService";
import { systemOrchestrator } from "@/lib/systemOrchestrator";

export const ShareCard: React.FC = () => {
  const { progress, gamification, userName, profile } = useAppStore();
  const canvasRef = React.useRef<HTMLCanvasElement>(null);
  const [isGenerating, setIsGenerating] = React.useState(false);

  const generateCard = async () => {
    setIsGenerating(true);
    const canvas = canvasRef.current;
    if (!canvas) return;

    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    // Canvas setup (high res)
    canvas.width = 1200;
    canvas.height = 630;

    // Background Gradient
    const grad = ctx.createLinearGradient(0, 0, 1200, 630);
    grad.addColorStop(0, "#0f172a");
    grad.addColorStop(1, "#1e293b");
    ctx.fillStyle = grad;
    ctx.fillRect(0, 0, 1200, 630);

    // Decorative elements
    ctx.strokeStyle = "rgba(59, 130, 246, 0.1)";
    ctx.lineWidth = 1;
    for (let i = 0; i < 1200; i += 50) {
      ctx.beginPath();
      ctx.moveTo(i, 0);
      ctx.lineTo(i, 630);
      ctx.stroke();
    }

    // Title
    ctx.fillStyle = "#ffffff";
    ctx.font = "black 40px 'Inter', sans-serif";
    ctx.textBaseline = "top";
    ctx.fillText("CIVIC AI ELECTION ASSISTANT", 80, 80);

    // Subtitle
    ctx.fillStyle = "#94a3b8";
    ctx.font = "bold 24px 'Inter', sans-serif";
    ctx.fillText("DEMOCRACY READINESS REPORT", 80, 140);

    // Main Readiness Score
    ctx.fillStyle = "#ffffff";
    ctx.font = "black 180px 'Inter', sans-serif";
    ctx.fillText(`${progress}%`, 80, 220);

    ctx.fillStyle = "#3b82f6";
    ctx.font = "bold 32px 'Inter', sans-serif";
    ctx.fillText("READY TO VOTE", 80, 420);

    // User Name
    ctx.fillStyle = "#ffffff";
    ctx.font = "bold 32px 'Inter', sans-serif";
    ctx.textAlign = "right";
    ctx.fillText(userName || profile.name || "CITIZEN", 1120, 80);

    // Points
    ctx.fillStyle = "#fbbf24";
    ctx.font = "black 48px 'Inter', sans-serif";
    ctx.fillText(`${gamification.points} PTS`, 1120, 140);

    // Draw Badges Section
    ctx.textAlign = "left";
    ctx.fillStyle = "rgba(255, 255, 255, 0.05)";
    ctx.roundRect?.(700, 220, 420, 330, 40);
    ctx.fill();

    ctx.fillStyle = "#ffffff";
    ctx.font = "bold 24px 'Inter', sans-serif";
    ctx.fillText("LATEST ACHIEVEMENTS", 740, 260);

    const unlockedBadges = gamification.badges.slice(-3);
    unlockedBadges.forEach((id, index) => {
      const b = getBadgeById(id);
      if (b) {
        ctx.font = "40px 'Inter'";
        ctx.fillText(b.icon, 740, 320 + (index * 70));
        ctx.fillStyle = "#ffffff";
        ctx.font = "bold 20px 'Inter', sans-serif";
        ctx.fillText(b.label.toUpperCase(), 800, 315 + (index * 70));
      }
    });

    // Logo / Footer
    ctx.fillStyle = "rgba(255,255,255,0.2)";
    ctx.font = "bold 18px 'Inter', sans-serif";
    ctx.fillText("Generated by Civic AI • Secure • Offline • Citizen First", 80, 560);

    setIsGenerating(false);
    return canvas.toDataURL("image/png");
  };

  const handleShare = async () => {
    const dataUrl = await generateCard();
    if (!dataUrl) return;

    try {
      if (navigator.share) {
        const blob = await (await fetch(dataUrl)).blob();
        const file = new File([blob], "readiness.png", { type: "image/png" });
        await navigator.share({
          title: "My Election Readiness",
          text: `I'm ${progress}% ready for the upcoming elections! Join me on Civic AI.`,
          files: [file],
        });
      } else {
        const link = document.createElement("a");
        link.download = "election-readiness.png";
        link.href = dataUrl;
        link.click();
      }
      systemOrchestrator.onStepComplete('share');
    } catch (error) {
      console.error("Share failed:", error);
    }
  };

  return (
    <Card className="p-8 bg-gradient-to-br from-blue-600 to-indigo-700 border-none shadow-3d overflow-hidden relative group">
      <div className="absolute top-0 right-0 w-64 h-64 bg-white/10 blur-[100px] -z-10" />
      
      <div className="flex flex-col md:flex-row items-center gap-8">
        <div className="flex-1 space-y-4 text-center md:text-left">
          <div className="flex items-center justify-center md:justify-start gap-2">
            <Share2 className="text-white/80" size={20} />
            <h3 className="text-2xl font-black text-white font-display uppercase tracking-tight">Share Your Progress</h3>
          </div>
          <p className="text-white/70 text-xs font-bold leading-relaxed max-w-sm">
            Generate your personalized readiness report and inspire your community to get registered and ready for the election.
          </p>
          <div className="flex flex-wrap items-center justify-center md:justify-start gap-3">
            <button 
              onClick={handleShare}
              disabled={isGenerating}
              className="px-6 py-3 bg-white text-blue-700 rounded-2xl text-[11px] font-black uppercase tracking-widest flex items-center gap-2 hover:bg-slate-100 transition-all shadow-xl shadow-blue-900/20"
            >
              {isGenerating ? "Generating..." : "Share Report"} <Share2 size={14} />
            </button>
            <button 
              onClick={handleShare}
              className="p-3 bg-white/10 text-white rounded-2xl hover:bg-white/20 transition-all"
            >
              <Download size={18} />
            </button>
          </div>
        </div>

        <div className="w-48 h-48 bg-white/10 backdrop-blur-md rounded-[2.5rem] border border-white/20 flex flex-col items-center justify-center p-6 relative overflow-hidden group-hover:scale-105 transition-transform duration-700">
          <div className="text-4xl font-black text-white font-display mb-1">{progress}%</div>
          <div className="text-[9px] font-black text-white/50 uppercase tracking-[0.2em]">Readiness</div>
          <div className="mt-4 flex gap-1">
            {[1, 2, 3, 4, 5].map((s) => (
              <div key={s} className={cn(
                "w-1.5 h-6 rounded-full",
                s <= (progress / 20) ? "bg-white" : "bg-white/20"
              )} />
            ))}
          </div>
        </div>
      </div>

      <canvas ref={canvasRef} style={{ display: "none" }} />
    </Card>
  );
};
